[package]
name = "c"
version = "0.1.0"
authors = ["0"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Common
serde = "1.0.111"
serde_json = "1.0.55"
itertools = "0.9.0"

# Seed
seed = "0.7.0"

# GraphQL
graphql_client = "0.9.0"
